server:
  port: 8192

spring:
  application:
    name: ticketera-auth
  datasource:
    username: user
    password: password
    url:  jdbc:postgresql://localhost:5432/authticketera
  flyway:
    url: jdbc:postgresql://localhost:5432/authticketera
    user: user
    password: password

jwtprops:
  secret: ilWsuZYs6rE8a6zo7VaTvHwMADbSniCxUwoszjdXvldRgMcKJmgo02mR4PwM03xSr7Ou3e9gfvnw9EkelBik7w==
  expiration: 3600000