server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  application:
    name: ticketera-auth
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/authticketera
  flyway:
    url: jdbc:postgresql://localhost:5432/authticketera
    user: user
    password: password

jwtprops:
  secret:
  expiration: 1800000
aws:
  region: eu-east-1
  key: "FAKEAWSACCESSKEY123456"
  secret: "FAKEAWSSECRETKEY1234567890"

email:
  enabled: true
  link: http://localhost:8080/auth/verify
  from: admin@opustix.com
  subject0: "Verify your email"
  message0: |
    hi... complete the message here!
  subject1: "Invalid Login"
  message1: |
    hi... complete the message here!
  subject2: "Invalid Sign-Up"
  message2: |
    hi... complete the message here!
  subject3: "Successfully Validated"
  message3: |
    hi... complete the message here!
  closing: complete the message here!
