version: "3.9"

services:
  signalsDB:
    image: "postgres:16.4"
    container_name: "auth-ticketera-db"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=authticketera
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
